language: java
sudo: false

before_install: echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc
install:
  -

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - CMD="mvn install --projects acceptance-tests --also-make --activate-profiles all --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="findbugs"
        - CMD="mvn install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests' --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn install checkstyle:check --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests"
        - CMD="mvn install --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="compile jmh-tests and performance-tests"
        - CMD="mvn install --projects jmh-tests,performance-tests --also-make --activate-profiles all -DskipTests=true --batch-mode --show-version --errors"

    - jdk: oraclejdk8
      env:
        - DESC="compile with Java 7"
        - CMD1="mvn install --projects eclipse-collections-code-generator,eclipse-collections-code-generator-maven-plugin -Dmaven.compiler.verbose=true --batch-mode --show-version --errors;"
        - CMD2="jdk_switcher use oraclejdk7;"
        - CMD3="mvn install --projects eclipse-collections,eclipse-collections-api,eclipse-collections-testutils,eclipse-collections-forkjoin,serialization-tests -Denforcer.skip=true -Dmaven.compiler.verbose=true --batch-mode --show-version --errors;"
        - CMD4="jdk_switcher use oraclejdk8;"
        - CMD5="mvn install --projects unit-tests,junit-trait-runner,unit-tests-java8 -Dmaven.compiler.verbose=true --batch-mode --show-version --errors"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5
script: eval $CMD

cache:
  directories:
  - ~/.m2
