language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
  -

env:
  -JDK=Java8
  -JDK=Java9
  -JDK=Java10
  -JDK=Java11-EA
  -JDK=Java12-EA

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - JDK=Java8
        - CMD="mvn install --projects acceptance-tests --also-make --activate-profiles all"

    - jdk: oraclejdk8
      env:
        - DESC="findbugs"
        - JDK=Java8
        - CMD="mvn install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests,!jcstress-tests,!p2-repository' --activate-profiles all -DskipTests=true"
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - JDK=Java8
        - CMD="mvn install checkstyle:check --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests"
        - JDK=Java8
        - CMD="mvn install"

    - jdk: oraclejdk8
      env:
        - DESC="compile performance-tests"
        - JDK=Java8
        - CMD="mvn install --projects performance-tests --also-make --activate-profiles all -DskipTests=true"

    - jdk: oraclejdk9
      env:
        - DESC="unit tests Java 9"
        - JDK=Java9
        - CMD="mvn install"

    - jdk: oraclejdk8
      env:
        - DESC="Java 10 regression"
        - JDK=Java10
        - CMD=""

    - jdk: oraclejdk8
      env:
        - DESC="Java 11 regression"
        - JDK=Java11-EA
        - CMD=""

    - jdk: oraclejdk8
      env:
        - DESC="Java 12 regression"
        - JDK=Java12-EA
        - CMD=""

  allow_failures:
  - jdk: oraclejdk8
    env:
      - DESC="Java 11 regression"
      - JDK=Java11-EA
      - CMD=""

  - jdk: oraclejdk8
    env:
      - DESC="Java 12 regression"
      - JDK=Java12-EA
      - CMD=""

script:
  - ./.travis-command-ea-builds.sh
  - eval travis_wait 55 $CMD

before_cache:
  - rm -rf $HOME/.m2/repository/org/eclipse/collections/

cache:
  directories:
    - $HOME/.m2
