language: java
dist: trusty
sudo: false

before_install:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g'" > ~/.mavenrc

install:
  -

jobs:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env:
        - DESC="acceptance tests"
        - CMD="./mvnw install --projects acceptance-tests --also-make --activate-profiles all --no-transfer-progress"

    - jdk: oraclejdk8
      env:
        - DESC="findbugs"
        - CMD="./mvnw install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests,!jcstress-tests,!p2-repository' --activate-profiles all -DskipTests=true --no-transfer-progress"

    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="./mvnw install checkstyle:check --activate-profiles all -DskipTests=true --no-transfer-progress"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests"
        - CMD="./mvnw install"

    - jdk: oraclejdk8
      env:
        - DESC="compile performance-tests"
        - CMD="./mvnw install --projects performance-tests --also-make --activate-profiles all -DskipTests=true --no-transfer-progress"

    - jdk: oraclejdk11
      env:
        - DESC="compile javadoc"
        - CMD="./mvnw install javadoc:jar --projects 'eclipse-collections-code-generator,eclipse-collections-code-generator-maven-plugin,eclipse-collections-api,eclipse-collections,eclipse-collections-testutils,eclipse-collections-forkjoin' --activate-profiles all -DskipTests=true --no-transfer-progress"

    - jdk: openjdk11
      env:
        - DESC="unit tests openjdk11"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: oraclejdk11
      env:
        - DESC="unit tests oraclejdk11"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: openjdk14
      env:
        - DESC="unit tests openjdk14"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: oraclejdk14
      env:
        - DESC="unit tests oraclejdk14"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: openjdk-ea
      env:
        - DESC="unit tests openjdk-ea"
        - CMD="./mvnw install --no-transfer-progress"

    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java15-EA"
        - JDK=Java15-EA
        - CMD="./.travis-command-ea-builds.sh"

  allow_failures:
    - jdk: openjdk-ea
      env:
        - DESC="unit tests openjdk-ea"
        - CMD="./mvnw install --no-transfer-progress"
    - jdk: oraclejdk8
      env:
        - DESC="unit tests Java15-EA"
        - JDK=Java15-EA
        - CMD="./.travis-command-ea-builds.sh"

script: eval travis_wait 30 $CMD

before_cache:
  - rm -rf $HOME/.m2/repository/org/eclipse/collections/

cache:
  directories:
    - $HOME/.m2
