# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Acceptance Tests

on: [push, pull_request]

jobs:
  applications:
    name: Acceptance Tests ${{ matrix.java-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set Maven Wrapper
        run: mvn --non-recursive wrapper:wrapper -Dmaven=3.9.6
      - name: Set JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Acceptance Tests
        run: ./mvnw install --projects acceptance-tests --also-make --activate-profiles all
        env:
          MAVEN_OPTS: "-Xmx1g"
